languageCode = "en-us"
title = "Prologue"
baseurl = "http://adityac8.github.io"
theme = "prologue"

[params]
  name = "Aditya Arora"
  description = "Machine Learning Intern"
  copyright = "channelCS"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "http://www.twitter.com/imAArora"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "http://www.facebook.com/adityaarorac8"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://www.github.com/adityac8"

[[params.social]]
  medium = "dribbble"
  icon = "dribbble"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "adityadvlp@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Ipsum Feugiat"
  alt = ""
  source = "img/face.png"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
